name: UltimateClans
main: me.ulrich.clans.Clans
version: 7.0.0
author: UlrichBR
website: https://polymart.org/team/ulrichcraft.99
description: The best and most complete system of clans and lands.
api-version: 1.13
folia-supported: true
softdepend: [ProtocolLib, Vault, PlaceholderAPI, WorldGuard, WorldEdit, CombatLogX, PlayerPoints, BlueMap, DeluxeCombat, PvPManager, floodgate, Duels, EconomyPlus, MythicMobs, dynmap, TitansBattle, HolographicDisplays, CMI, Holograms, DecentHolograms, ItemsAdder, TokenEnchant, SkinsRestorer, EcoBosses, EcoItems, EnchantmentSolution, NBTAPI, LevelledMobs, ElementalGems]
commands:
   uclan:
      description: Open the help staff menu.
      usage: /<command>
      aliases: [uclans, uc, ugang, ug, uteam]
   clan:
      description: Open the help player menu.
      usage: /<command>
      aliases: [clans, c, gang, team, guild, guilda]
